services:
  - type: web
    name: devablueforex-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        value: 11devablue72
      - key: NODE_ENV
        value: production
